module.exports = {
	CHAT_STATUSES: {
		PENDING: "PENDING",
		ACCEPTED: "ACCEPTED",
		DISCONNECTED: "DISCONNECTED",
	},
	KEY_GENERATION_STATUES: {
		IN_PROGRESS: "IN PROGRESS",
		SUCCESS: "SUCCESS",
		FAIL: "FAIL",
	}
};
